/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    // All photo sizes are pre-generated by scripts/optimize-images.mjs and served
    // as static files; the loader maps each requested width to one of them.
    loader: 'custom',
    loaderFile: './src/lib/image-loader.ts',
    // Must match the widths the script generates (see TARGETS there).
    deviceSizes: [640, 960, 1280, 1920],
    imageSizes: [128, 384],
  },
  async headers() {
    return [
      {
        // Photos are content-addressed by the optimiser run; cache them hard.
        source: '/images/:path*',
        headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
      },
    ];
  },
};

export default nextConfig;
