import Image from 'next/image';
import { SLOT_IMAGES } from '@/lib/slot-images';
import { BLUR_DATA } from '@/lib/blur-data';

/**
 * Static port of the design's <image-slot>.
 *
 * Filled slots render through next/image: responsive srcset (driven by `sizes`)
 * served from the static sizes pre-generated by scripts/optimize-images.mjs
 * (see src/lib/image-loader.ts), native lazy loading, and a blurred preview
 * from src/lib/blur-data.ts while the photo streams in. Pass `priority` for the one
 * image that is above the fold on a page so it is preloaded instead of lazy.
 *
 * Add photos by mapping `slot id -> /images/…` in src/lib/slot-images.ts and
 * running `node scripts/optimize-images.mjs`.
 */
type Props = {
  id: string;
  placeholder: string;
  /** CSS `sizes` hint: how wide this slot renders. Defaults to full width. */
  sizes?: string;
  /** Preload instead of lazy-load (above-the-fold images only). */
  priority?: boolean;
};

export default function ImageSlot({ id, placeholder, sizes = '100vw', priority = false }: Props) {
  const src = SLOT_IMAGES[id];

  if (src) {
    const blur = BLUR_DATA[src];
    return (
      <div className="slot slot-filled">
        <Image
          src={src}
          alt={placeholder}
          fill
          sizes={sizes}
          priority={priority}
          placeholder={blur ? 'blur' : 'empty'}
          blurDataURL={blur}
        />
      </div>
    );
  }

  return (
    <div className="slot">
      <div className="slot-empty">
        <svg
          width="28"
          height="28"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.6"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <rect x="3" y="3" width="18" height="18" rx="2" />
          <circle cx="8.5" cy="8.5" r="1.5" />
          <path d="m21 15-5-5L5 21" />
        </svg>
        <div className="cap">{placeholder}</div>
      </div>
      <div className="slot-ring" />
    </div>
  );
}
