/**
 * Optimise site photos for the web.
 *
 *   node scripts/optimize-images.mjs
 *
 * - Converts every .png/.jpg/.jpeg under public/images/** (and the hero background
 *   in public/assets) to WebP, capped at a sensible width, and removes the original.
 * - Regenerates src/lib/blur-data.ts: a tiny base64 preview per image that
 *   <ImageSlot> shows while the real photo streams in.
 *
 * Re-run it whenever you drop new photos into public/images.
 */
import sharp from 'sharp';
import { readdirSync, statSync, unlinkSync, writeFileSync } from 'fs';
import { join, extname, basename, dirname, sep } from 'path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const TARGETS = [
  { dir: 'public/images/menu', maxWidth: 1200 },
  { dir: 'public/images/home', maxWidth: 1920 },
  { dir: 'public/assets', maxWidth: 1920, only: /^hero-bg\./ },
];
const QUALITY = 80;

const walk = (d) => readdirSync(d).flatMap((f) => {
  const p = join(d, f);
  return statSync(p).isDirectory() ? walk(p) : [p];
});

let before = 0, after = 0;
for (const t of TARGETS) {
  const dir = join(ROOT, t.dir);
  for (const file of walk(dir)) {
    const ext = extname(file).toLowerCase();
    if (!['.png', '.jpg', '.jpeg'].includes(ext)) continue;
    if (t.only && !t.only.test(basename(file))) continue;
    const out = join(dirname(file), basename(file, ext) + '.webp');
    const src = statSync(file).size;
    await sharp(file)
      .rotate()
      .resize({ width: t.maxWidth, withoutEnlargement: true })
      .webp({ quality: QUALITY, effort: 5 })
      .toFile(out);
    const dst = statSync(out).size;
    before += src; after += dst;
    unlinkSync(file);
    console.log(`${basename(file)} -> ${basename(out)}  ${(src / 1024).toFixed(0)}KB -> ${(dst / 1024).toFixed(0)}KB`);
  }
}
if (before) console.log(`\nConverted: ${(before / 1048576).toFixed(1)}MB -> ${(after / 1048576).toFixed(1)}MB`);

// Blur placeholders for every optimised image.
const blur = {};
for (const t of TARGETS) {
  for (const file of walk(join(ROOT, t.dir))) {
    if (extname(file) !== '.webp') continue;
    if (t.only && !t.only.test(basename(file))) continue;
    const buf = await sharp(file).resize({ width: 10 }).webp({ quality: 30 }).toBuffer();
    const url = '/' + file.slice(join(ROOT, 'public').length + 1).split(sep).join('/');
    blur[url] = `data:image/webp;base64,${buf.toString('base64')}`;
  }
}
const lines = Object.keys(blur).sort().map((k) => `  '${k}': '${blur[k]}',`);
writeFileSync(
  join(ROOT, 'src/lib/blur-data.ts'),
  `// Generated by scripts/optimize-images.mjs — do not edit by hand.\n// Tiny base64 previews shown while each photo loads.\nexport const BLUR_DATA: Record<string, string> = {\n${lines.join('\n')}\n};\n`,
);
console.log(`Wrote src/lib/blur-data.ts (${lines.length} entries)`);
